title: Wocker
description: Docker-based rapid WordPress development environment. IT TAKES JUST 3 SECONDS TO CREATE EVERY FRESH WORDPRESS ENVIRONMENT!

baseurl: ""
url: https://wckr.github.io

exclude:
  - node_modules
  - gulpfile.js
  - gulpconfig.json
  - package.json
  - package-lock.json
  - npm-debug.log
  - README.md
  - LICENSE
  - config.rb

github:
  org: wckr
  repo: wocker
  admin: ixkaito
facebook:
  id: kite.koga
twitter:
  id: ixkaito

images_dir: /assets/images
css_dir: /assets/css
js_dir: /assets/js

ogp_image: /ogp-image.png

version: 1.2
