title: Wocker
description: Docker-based rapid development environment of WordPress. IT TAKES JUST 3 SECONDS TO CREATE A NEW ONE!

baseurl: ""
url: https://wckr.github.io

exclude:
  - node_modules
  - gulpfile.js
  - gulpconfig.json
  - package.json
  - npm-debug.log
  - README.md
  - LICENSE
  - config.rb

github_user: ixkaito
github_org: wckr
github_repo: wocker
facebook_user: kite.koga
twitter_user: ixkaito

images_dir: /assets/images
css_dir: /assets/css
js_dir: /assets/js

ogp_image: /ogp-image.png

version: 1.1.2
